// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_KHBJkAyFXCxok6SfnTvDJpomw7D6bRs',
    appId: '1:406741721329:web:235262f08ba2ea87060950',
    messagingSenderId: '406741721329',
    projectId: 'ddea-1d472',
    authDomain: 'ddea-1d472.firebaseapp.com',
    storageBucket: 'ddea-1d472.appspot.com',
    measurementId: 'G-YXJQSDLN5F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfHQ_Ejm0aqYNuwrKfCPx-6O5AYKKb6ic',
    appId: '1:406741721329:android:b2f3cd4e1e0292ca060950',
    messagingSenderId: '406741721329',
    projectId: 'ddea-1d472',
    storageBucket: 'ddea-1d472.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAVCZgYYMwaYh4Q89GxowRt-52PwHQFYg',
    appId: '1:406741721329:ios:8eaf30569a877041060950',
    messagingSenderId: '406741721329',
    projectId: 'ddea-1d472',
    storageBucket: 'ddea-1d472.appspot.com',
    iosClientId: '406741721329-vsu2p5r3lnr0gpp5b2ieq8djdj8nlkj6.apps.googleusercontent.com',
    iosBundleId: 'com.example.ddeaOfficial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAVCZgYYMwaYh4Q89GxowRt-52PwHQFYg',
    appId: '1:406741721329:ios:8eaf30569a877041060950',
    messagingSenderId: '406741721329',
    projectId: 'ddea-1d472',
    storageBucket: 'ddea-1d472.appspot.com',
    iosClientId: '406741721329-vsu2p5r3lnr0gpp5b2ieq8djdj8nlkj6.apps.googleusercontent.com',
    iosBundleId: 'com.example.ddeaOfficial',
  );
}
